apiVersion: v1
kind: Secret
metadata:
    name: azure-secret-sp
    namespace: external-secrets-system
type: Opaque
stringData:
    ClientID: ENC[AES256_GCM,data:izeyUBAEKyAL57zuVmRsYw58w6lzWBBIzDsRVmotDOOjvE/E,iv:bkkdBuZWXRaeIOmAu6+dBDpoPKEGr0OfNYwD7pm9rV4=,tag:oC5F43qJn+oXWbOvhcrw3g==,type:str]
    ClientSecret: ENC[AES256_GCM,data:FijaOEHNKGPBwS7vHC1aZaqPARwCAMHtXlVgTbXcSiIOIJs7FuLphg==,iv:dablEs5ze6u+fPxSSe9gFIKE+mjorAMn5yq3PeCVads=,tag:Z1JPMxk1UwoLHWNhSmuDjg==,type:str]
sops:
    age:
        - recipient: age1u9v9s8xxz66e77wr04dqr0zgpw5vs3j56njm45jp65fkafgasfrqsf8t2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRHd6bGhEelRVaWFDbUYz
            NmdmTEdZTm5yb3p6ckdVY2RXTkxZRndqZ2xzCmhrQmhXOFBTcnNjRXpEamY0MkJi
            aXIvUDRGNnMzZk1GTTc1YTdIMVJDR2cKLS0tIGJza2tQWEtGODU4TXAvcklhWGs5
            Q2VJS2dhc1FTT21jV29kRDNnNHlMcHcKkhd/jrfXFBQmF0dlF/nhD+In++ooOwT3
            qQHptGN4YUOJbgxJi8OEEa6UZzs28xjz2tzQOcfczrsgrvQFQcfrcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T13:48:30Z"
    mac: ENC[AES256_GCM,data:KcCiscX3VpJAkEDlpmwTdgyXU0aTH9SxfGtpao39/QD1pZf3ix6n4OeOP+QMrK4g9B9ETo3a3qB6EucNrhDnNfEDX45g/clZpIycIazcEZs/jzkSGHng2cY/oCtYcmegaBzJHsrBQHhluBvkC6XaDrFpaPZU4xAeQQkRxQxxvB4=,iv:pCcLDyXpuG9AndKnGIW8dUCE+5MErG/5J5+nO+zFwrs=,tag:UJy/3hZCLIb+ClV8l8KSlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
