apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.0.50
  share: /srv/nfs/k8s # ← Adjust to your NFS export path
  # Optional: Subdirectory pattern for PVCs
  # subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
reclaimPolicy: Retain # or Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - hard
  - timeo=600
  - retrans=2
  - rsize=1048576
  - wsize=1048576
