# Phase 1: Monitoring Secrets (no dependencies)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-monitoring-secrets
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/config/lothbrok/monitoring
  prune: true
  wait: true
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# Phase 2: Infrastructure controllers (depends on monitoring secrets)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/controllers/lothbrok
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:
    - name: infrastructure-monitoring-secrets

  postBuild:
    substituteFrom:
      - kind: Secret
        name: monitoring-secrets
        optional: false

  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# Phase 3: Other secrets (depends on infrastructure controllers)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-secrets
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/config/lothbrok/secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
# Phase 4: Resources configuration (depends on secrets)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infrastructure-secrets
    - name: infrastructure-monitoring-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/config/lothbrok/resources
  prune: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: metallb-ip-pools
        optional: false
      - kind: Secret
        name: monitoring-secrets
        optional: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
