apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: linkding.pjfaraon.net
        service: http://linkding.linkding.svc.cluster.local:9090
      - hostname: pgadmin.pjfaraon.net
        service: http://pgadmin.pgadmin.svc.cluster.local:80
      - hostname: "*.pjfaraon.net"
        service: http://traefik.traefik.svc.cluster.local:80
      - service: http_status:404
