apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: metallb-ip-pools
  namespace: metallb-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store
  target:
    name: metallb-ip-pools
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ingress-pool: "{{ .ingresspool }}"
        services-pool: "{{ .servicespool }}"
        database-pool: "{{ .databasepool }}"
        reserved-pool: "{{ .reservedpool }}"
  data:
    - secretKey: ingresspool
      remoteRef:
        key: metallb-ingress-pool
    - secretKey: servicespool
      remoteRef:
        key: metallb-services-pool
    - secretKey: databasepool
      remoteRef:
        key: metallb-database-pool
    - secretKey: reservedpool
      remoteRef:
        key: metallb-reserved-pool
