apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azdo-pat
  namespace: azure-devops
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore

  target:
    name: azdo-pat
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"

  data:
    - secretKey: token
      remoteRef:
        key: azdo-pat-token
