apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-db-credentials
  namespace: linkding
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: linkding-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        database: "{{ .database }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
        host: "linkding-postgres-rw.linkding.svc.cluster.local"
        port: "5432"
        DATABASE_URL: "postgres://{{ .username }}:{{ .password }}@linkding-postgres-rw.linkding.svc.cluster.local:5432/{{ .database }}"
  data:
    - secretKey: database
      remoteRef:
        key: linkding-db-name
    - secretKey: username
      remoteRef:
        key: linkding-db-username
    - secretKey: password
      remoteRef:
        key: linkding-db-password
