apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-postgres
  namespace: linkding
spec:
  instances: 3

  # PostgreSQL 16
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6

  # Storage configuration
  storage:
    size: 10Gi
    storageClass: local-path

  # Monitoring
  monitoring:
    enablePodMonitor: true

  # Bootstrap
  bootstrap:
    initdb:
      database: linkding
      owner: linkding
      secret:
        name: linkding-postgres-superuser

  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      work_mem: "4MB"
      wal_buffers: "8MB"
      min_wal_size: "80MB"
      max_wal_size: "1GB"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      log_destination: "stderr"
      logging_collector: "on"
      log_line_prefix: "%m [%p] %q%u@%d "
      log_timezone: "UTC"

  # Resources
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
