apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: metallb-ip-pools
  namespace: metallb-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: metallb-ip-pools
    creationPolicy: Owner
  data:
    - secretKey: ingress-pool
      remoteRef:
        key: metallb-ingress-pool
    - secretKey: services-pool
      remoteRef:
        key: metallb-services-pool
    - secretKey: database-pool
      remoteRef:
        key: metallb-database-pool
    - secretKey: reserved-pool
      remoteRef:
        key: metallb-reserved-pool
