apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metallb-ip-pools
  namespace: flux-system
  annotations:
    description: "MetalLB IP pool ranges sourced from Azure Key Vault"
    usage: "Used by Flux Kustomization postBuild.substituteFrom for variable substitution"
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: metallb-ip-pools
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: metallb
          app.kubernetes.io/component: ip-pools
          app.kubernetes.io/part-of: networking
        annotations:
          description: "IP ranges for MetalLB load balancer pools"
          source: "azure-keyvault"
  data:
    - secretKey: INGRESS_POOL
      remoteRef:
        key: metallb-ingress-pool
    - secretKey: SERVICES_POOL
      remoteRef:
        key: metallb-services-pool
    - secretKey: DATABASE_POOL
      remoteRef:
        key: metallb-database-pool
    - secretKey: RESERVED_POOL
      remoteRef:
        key: metallb-reserved-pool
