apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin-tls
  namespace: pgadmin
  annotations:
    description: "SSL certificate for local-only pgAdmin access"
spec:
  secretName: pgadmin-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - pgadmin.local.pjfaraon.net
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days before expiry
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
