apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: pgadmin-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: pgadmin-password
