apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
    - name: metallb
      namespace: flux-system
  chart:
    spec:
      chart: traefik
      version: "32.1.1"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 12h
  releaseName: traefik
  targetNamespace: traefik
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: ingress-pool
    ports:
      web:
        port: 80
        exposedPort: 80
      websecure:
        port: 443
        exposedPort: 443
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.localhost`)
        entryPoints: ["web"]
    logs:
      general:
        level: INFO
      access:
        enabled: true
