apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
        policy-type: "app"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: linkding
          image: sissbruecker/linkding:1.39.1
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

          ports:
            - containerPort: 8008
              protocol: TCP

          env:
            - name: LD_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: linkding-secrets
                  key: LD_SUPERUSER_NAME
            - name: LD_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-secrets
                  key: LD_SUPERUSER_PASSWORD

          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data

      restartPolicy: Always

      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data
