apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
        policy-type: "app"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: linkding
          image: sissbruecker/linkding:1.39.1
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

          ports:
            - containerPort: 9090
              protocol: TCP

          env:
            - name: LD_SUPERUSER_NAME
              valueFrom:
                secretKeyRef:
                  name: linkding-secrets
                  key: LD_SUPERUSER_NAME
            - name: LD_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-secrets
                  key: LD_SUPERUSER_PASSWORD

            - name: LD_DB_ENGINE
              value: "postgres"

            - name: LD_DB_HOST
              value: "linkding-postgres-rw.linkding.svc.cluster.local"

            - name: LD_DB_PORT
              value: "5432"

            - name: LD_DB_NAME
              value: "linkding"

            - name: LD_DB_USER
              valueFrom:
                secretKeyRef:
                  name: linkding-db-credentials
                  key: username

            - name: LD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: linkding-db-credentials
                  key: password

          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data

      restartPolicy: Always

      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data
