apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkding-credentials
  namespace: linkding
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: linkding-secrets
    creationPolicy: Owner
  data:
    - secretKey: LD_SUPERUSER_NAME
      remoteRef:
        key: linkding-superuser-name
    - secretKey: LD_SUPERUSER_PASSWORD
      remoteRef:
        key: linkding-superuser-password
