apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-env
  namespace: renovate
data:
  RENOVATE_PLATFORM: "github"
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_GIT_AUTHOR: "PJ's Renovate Bot <bot@renovateapp.com>"
  LOG_LEVEL: "debug"
