apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-docker-config
  namespace: renovate
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: renovate-docker-config
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfig | toString }}"
  data:
    - secretKey: dockerconfig
      remoteRef:
        key: renovate-docker-config
