apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secret
  namespace: renovate
spec:
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: renovate-secret
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovate-github-token
